<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PurchaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('purchases')->insert([
            [
                'id' => 1,
                'name' => 'Molde',
                'observations' => null,
                'quantity' => 1.00,
                'unit_id' => 1,
                'price' => 50.00,
                'total' => 50.00,
                'supplier_id' => 1,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 2,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:01:18',
                'updated_at' => '2025-08-12 07:01:18',
            ],
            [
                'id' => 2,
                'name' => 'Escalado',
                'observations' => null,
                'quantity' => 1.00,
                'unit_id' => 1,
                'price' => 20.00,
                'total' => 20.00,
                'supplier_id' => 1,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 2,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:02:17',
                'updated_at' => '2025-08-12 07:12:44',
            ],
            [
                'id' => 3,
                'name' => 'Ploteo',
                'observations' => null,
                'quantity' => 1.00,
                'unit_id' => 1,
                'price' => 7.00,
                'total' => 7.00,
                'supplier_id' => 1,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 2,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:25:23',
                'updated_at' => '2025-08-12 07:25:23',
            ],
            [
                'id' => 4,
                'name' => 'Muestra casaca suede',
                'observations' => null,
                'quantity' => 1.00,
                'unit_id' => 1,
                'price' => 37.50,
                'total' => 37.50,
                'supplier_id' => 2,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 3,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:27:38',
                'updated_at' => '2025-08-12 07:27:38',
            ],
            [
                'id' => 5,
                'name' => 'Franela Biege C#4',
                'observations' => null,
                'quantity' => 36.00,
                'unit_id' => 3,
                'price' => 12.00,
                'total' => 432.00,
                'supplier_id' => 3,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:28:56',
                'updated_at' => '2025-08-12 07:32:10',
            ],
            [
                'id' => 6,
                'name' => 'Franela Cholocate C#7',
                'observations' => null,
                'quantity' => 65.80,
                'unit_id' => 3,
                'price' => 12.00,
                'total' => 789.60,
                'supplier_id' => 3,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:29:19',
                'updated_at' => '2025-08-12 07:32:24',
            ],
            [
                'id' => 7,
                'name' => 'Franela Laurel C#10',
                'observations' => null,
                'quantity' => 67.10,
                'unit_id' => 3,
                'price' => 12.00,
                'total' => 805.20,
                'supplier_id' => 3,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:30:41',
                'updated_at' => '2025-08-12 07:32:43',
            ],
            [
                'id' => 8,
                'name' => 'Tafeta',
                'observations' => null,
                'quantity' => 169.00,
                'unit_id' => 3,
                'price' => 3.00,
                'total' => 507.00,
                'supplier_id' => 4,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:31:57',
                'updated_at' => '2025-08-12 07:31:57',
            ],
            [
                'id' => 9,
                'name' => 'Cortes de frnalea y tafeta',
                'observations' => "Laurel 24 (S) y 24 (M)\nBeige 13 (S) y 13 (M)\nChocolate 26 (S) y 26 (M)",
                'quantity' => 126.00,
                'unit_id' => 1,
                'price' => 1.60,
                'total' => 201.60,
                'supplier_id' => 5,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 5,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:34:03',
                'updated_at' => '2025-08-12 07:34:03',
            ],
            [
                'id' => 10,
                'name' => 'Confeccion Yoni',
                'observations' => null,
                'quantity' => 126.00,
                'unit_id' => 1,
                'price' => 15.00,
                'total' => 1890.00,
                'supplier_id' => 2,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 6,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:34:34',
                'updated_at' => '2025-08-12 07:34:34',
            ],
            [
                'id' => 11,
                'name' => 'Cierres Beige Chocolate y Laurel',
                'observations' => "Los cierres miden 49.5cms (S) y 51.5cms (M)\n\nBeige 14 (S) y 14 (M)\nChocolate27 (S) y 27 (M)\nLaurel 25 (S) y 25 (M)\n\nEl tenido\n\n14.50, 10 y 15.8 los cierres em si 440 soles\nhay una diferencia de 40 soles que no es consistente",
                'quantity' => 132.00,
                'unit_id' => 1,
                'price' => 3.94,
                'total' => 520.30,
                'supplier_id' => 6,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 7,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:38:06',
                'updated_at' => '2025-08-12 07:38:06',
            ],
            [
                'id' => 12,
                'name' => 'Broches',
                'observations' => null,
                'quantity' => 3.00,
                'unit_id' => 5,
                'price' => 40.00,
                'total' => 120.00,
                'supplier_id' => 7,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 7,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:38:49',
                'updated_at' => '2025-08-12 07:38:49',
            ],
            [
                'id' => 13,
                'name' => 'Servicio de Broche',
                'observations' => null,
                'quantity' => 120.00,
                'unit_id' => 1,
                'price' => 0.63,
                'total' => 75.60,
                'supplier_id' => 8,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 7,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 1,
                'created_at' => '2025-08-12 07:39:11',
                'updated_at' => '2025-08-12 07:39:11',
            ],
            [
                'id' => 14,
                'name' => 'franela color pecana',
                'observations' => null,
                'quantity' => 19.65,
                'unit_id' => 2,
                'price' => 26.50,
                'total' => 520.72,
                'supplier_id' => 9,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-13 05:21:09',
                'updated_at' => '2025-08-13 05:21:09',
            ],
            [
                'id' => 15,
                'name' => 'franela color beige',
                'observations' => null,
                'quantity' => 21.95,
                'unit_id' => 2,
                'price' => 26.00,
                'total' => 570.70,
                'supplier_id' => 10,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-13 05:24:39',
                'updated_at' => '2025-08-13 05:24:39',
            ],
            [
                'id' => 16,
                'name' => 'franela color verde sauce',
                'observations' => null,
                'quantity' => 22.25,
                'unit_id' => 2,
                'price' => 26.50,
                'total' => 589.63,
                'supplier_id' => 9,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-13 05:26:01',
                'updated_at' => '2025-08-13 05:26:01',
            ],
            [
                'id' => 17,
                'name' => 'yersey verde olivo',
                'observations' => null,
                'quantity' => 2.50,
                'unit_id' => 2,
                'price' => 30.00,
                'total' => 75.00,
                'supplier_id' => 11,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-13 05:47:10',
                'updated_at' => '2025-08-13 05:47:10',
            ],
            [
                'id' => 18,
                'name' => 'yersey beige',
                'observations' => null,
                'quantity' => 2.50,
                'unit_id' => 2,
                'price' => 31.00,
                'total' => 77.50,
                'supplier_id' => 10,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-13 05:48:20',
                'updated_at' => '2025-08-13 05:48:20',
            ],
            [
                'id' => 19,
                'name' => 'yersey 30/1 chocolate',
                'observations' => null,
                'quantity' => 2.50,
                'unit_id' => 2,
                'price' => 31.00,
                'total' => 77.50,
                'supplier_id' => 10,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-13 05:49:05',
                'updated_at' => '2025-08-13 05:49:05',
            ],
            [
                'id' => 20,
                'name' => 'pasadores',
                'observations' => null,
                'quantity' => 100.00,
                'unit_id' => 1,
                'price' => 0.76,
                'total' => 75.60,
                'supplier_id' => 12,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 4,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-13 05:54:15',
                'updated_at' => '2025-08-13 05:54:15',
            ],
            [
                'id' => 21,
                'name' => 'Servicio de Multiagujas',
                'observations' => null,
                'quantity' => 99.00,
                'unit_id' => 1,
                'price' => 0.70,
                'total' => 69.30,
                'supplier_id' => 13,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 7,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-13 05:58:09',
                'updated_at' => '2025-08-13 05:58:09',
            ],
            [
                'id' => 22,
                'name' => 'confección de palazo',
                'observations' => null,
                'quantity' => 99.00,
                'unit_id' => 1,
                'price' => 5.00,
                'total' => 495.00,
                'supplier_id' => 14,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 6,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-15 08:49:37',
                'updated_at' => '2025-08-15 08:49:37',
            ],
            [
                'id' => 23,
                'name' => 'corte de palazo',
                'observations' => null,
                'quantity' => 99.00,
                'unit_id' => 1,
                'price' => 0.81,
                'total' => 80.00,
                'supplier_id' => 15,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 5,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-15 08:54:41',
                'updated_at' => '2025-08-15 08:54:41',
            ],
            [
                'id' => 24,
                'name' => 'elástico 5cm mercializado',
                'observations' => null,
                'quantity' => 2.00,
                'unit_id' => 1,
                'price' => 25.00,
                'total' => 50.00,
                'supplier_id' => 16,
                'user_id' => 1,
                'store_id' => 1,
                'section_id' => 7,
                'purchaseable_type' => 'App\\Models\\Batch',
                'purchaseable_id' => 2,
                'created_at' => '2025-08-15 08:59:39',
                'updated_at' => '2025-08-15 08:59:39',

            ]
        ]);
    }
}
