<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

       DB::table('suppliers')->insert([
            [
                'id' => 1,
                'name' => 'Sra Padid',
                'address' => 'San Pedro Piso 10',
                'email' => null,
                'store_id' => 1,
                'phone' => '997057384',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-12 06:47:25',
                'updated_at' => '2025-08-12 06:47:25',
            ],
            [
                'id' => 2,
                'name' => 'Yoni',
                'address' => 'Mercado la Polvora 3er piso',
                'email' => null,
                'store_id' => 1,
                'phone' => '989620873',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-12 06:47:25',
                'updated_at' => '2025-08-12 06:47:25',
            ],
            [
                'id' => 3,
                'name' => 'Flotex (Alejandro)',
                'address' => 'Jr. Antonio Bazo 1070, La Victoria',
                'email' => null,
                'store_id' => 1,
                'phone' => '933560867',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-12 06:47:25',
                'updated_at' => '2025-08-12 06:47:25',
            ],
            [
                'id' => 4,
                'name' => 'Comercial Reynaldo',
                'address' => 'Galeria Sucre 1er Piso',
                'email' => null,
                'store_id' => 1,
                'phone' => '946158238',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-12 06:47:25',
                'updated_at' => '2025-08-12 06:47:25',
            ],
            [
                'id' => 5,
                'name' => 'Elmer',
                'address' => 'Parinacochas con humbolt',
                'email' => null,
                'store_id' => 1,
                'phone' => '963796086',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-12 06:47:25',
                'updated_at' => '2025-08-12 06:47:25',
            ],
            [
                'id' => 6,
                'name' => 'Cecilia Import Export Matias EIRL',
                'address' => 'Galeria La victoria Interior C221',
                'email' => null,
                'store_id' => 1,
                'phone' => '970390875',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-12 06:47:25',
                'updated_at' => '2025-08-12 06:47:25',
            ],
            [
                'id' => 7,
                'name' => 'Leoncia Roque',
                'address' => 'Galeria Leo',
                'email' => null,
                'store_id' => 1,
                'phone' => '662',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-12 06:47:25',
                'updated_at' => '2025-08-12 06:47:25',
            ],
            [
                'id' => 8,
                'name' => 'Martin Paiva',
                'address' => 'Galeria San Pedro 0316 (Sotano 3)',
                'email' => null,
                'store_id' => 1,
                'phone' => '980268638',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-12 06:47:25',
                'updated_at' => '2025-08-12 06:47:25',
            ],
            [
                'id' => 9,
                'name' => 'textil delgado',
                'address' => 'giribaldi 555 ( galería casas )  interior  211',
                'email' => null,
                'store_id' => 1,
                'phone' => '994052289',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-13 05:04:17',
                'updated_at' => '2025-08-13 05:04:17',
            ],
            [
                'id' => 10,
                'name' => 'yafeth',
                'address' => 'giribaldi 566 ( galería casas) interior 410',
                'email' => null,
                'store_id' => 1,
                'phone' => '908816013',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-13 05:24:24',
                'updated_at' => '2025-08-13 05:24:24',
            ],
            [
                'id' => 11,
                'name' => 'textiles camello',
                'address' => 'giribaldi 566 ( galería casas) interior 104',
                'email' => null,
                'store_id' => 1,
                'phone' => '983552213',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-13 05:46:58',
                'updated_at' => '2025-08-13 05:46:58',
            ],
            [
                'id' => 12,
                'name' => 'Bianca',
                'address' => 'Antonio bazo 727 interior 03',
                'email' => null,
                'store_id' => 1,
                'phone' => '981502570',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-13 05:54:08',
                'updated_at' => '2025-08-13 05:54:08',
            ],
            [
                'id' => 13,
                'name' => 'servicio multiagujas y ojal',
                'address' => 'galería San Pedro tienda 0211',
                'email' => null,
                'store_id' => 1,
                'phone' => '906829413',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-13 05:57:59',
                'updated_at' => '2025-08-13 05:57:59',
            ],
            [
                'id' => 14,
                'name' => 'señora rosa',
                'address' => 'casa',
                'email' => null,
                'store_id' => 1,
                'phone' => '992283456',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-15 08:49:26',
                'updated_at' => '2025-08-15 08:49:26',
            ],
            [
                'id' => 15,
                'name' => 'señor floridez',
                'address' => 'san Pedro tienda 733',
                'email' => null,
                'store_id' => 1,
                'phone' => '981926603',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-15 08:54:36',
                'updated_at' => '2025-08-15 08:54:36',
            ],
            [
                'id' => 16,
                'name' => 'señora elástico',
                'address' => 'galería la victoria tienda 02',
                'email' => null,
                'store_id' => 1,
                'phone' => '9999999',
                'identity_id' => 1,
                'document_number' => null,
                'created_at' => '2025-08-15 08:59:36',
                'updated_at' => '2025-08-15 08:59:36',
            ],
        ]);

    }
}
